### ISSUE TITLE
Cannot restore session after page refresh

### ISSUE THREAD

**Issue by rbartoli** [fenichelar/ember-simple-auth-token#10]
It seems I cannot find a way to restore the session on page reload.

As soon as the session is authenticated, localStorage contains the correct data. Then if I refresh the page I get redirected to the login page and localStorage is empty.

Is this supposed to be the standard behavior?

**Comment by jpadilla** [comment]
@rbartoli I've seen this happen before and I'm pretty sure it's an expected behavior of ember-simple-auth when authorization fails. You could check the request headers of the authorized requests, they should be failing.

https://github.com/simplabs/ember-simple-auth/blob/master/packages/ember-simple-auth/lib/simple-auth/mixins/application-route-mixin.js#L204

**Comment by rbartoli** [comment]
@jpadilla Thanks for your reply. In my case the authorization is succeeding and after logging in I get redirected to the route I specified in the "routeAfterAuthentication" property and the localStorage is filled with the data sent in the server response. But when I reload the page I'm sent back to the "login" route and localStorage is empty.

Something similar to this: http://stackoverflow.com/questions/25215010/ember-simple-auth-session-lost-on-refresh but the solution there works only for the ember-simple-auth-devise

**Comment by rbartoli** [comment]
@jpadilla What's the condition for the restore function to restore the previous session data?

https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/app/authenticators/token.js#L76

**Comment by jpadilla** [comment]
@rbartoli could you share what's the response your storing on localstorage? I think the problem might actually be there with line 76. If there's no `token` property found. If you have a different [tokenPropertyName](https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/app/authorizers/token.js#L53) it should be failing because of that.

If that's what's happening, definitely a bug.

**Comment by rbartoli** [comment]
@jpadilla I can confirm the issue. I was using "authToken" as [tokenPropertyName](https://github.com/jpadilla/ember-cli-simple-auth-token/blob/master/app/authorizers/token.js#L53) and it wasn't working. However as soon as I changed it to "token" I was able to reload the page without losing the session. As you can see I've created a pull request that fixes this bug. Please let me know what you think.

**Comment by knownasilya** [comment]
This still seems to be an issue, at least with the latest version and simple-auth beta.2

the restore method is never called.

**Comment by knownasilya** [comment]
Nevermind, I found `timeFactor`, which fixed the issue (`restore` was being called) since the token had the time in seconds not milliseconds.
