### ISSUE TITLE
request for documentation

### ISSUE THREAD

**Issue by ptmoy2** [fenichelar/ember-simple-auth-token#119]
I have an Ember application with a backend coded using Erlang.  Application currently uses an extremely clumsy server-side authentication mechanism.  I would like to change to token-based authentication.  I'm hoping to implement something fairly simple:

```
 1) Ember app sends login Id and password to server.
 2) Server authenticates and sends back a simple token, or JWT.
 3) Ember app sends this token on subsequent requests, or a logoff
      message if user logs off.
```

Sounds like this add-on, along with Ember-Simple-Auth can take care of the Ember side.  What I"m looking for is guidance on how to implement the server messages.  Basically, what I need is some documentation of the HTTP messages the server will be receiving from this addon so that I can handle those appropriately (e.g., what's the login HTTP message look like; where in the HTTP message does the token have to go in the server-reply message; where's the token in the subsequent authorize messages; what's the logoff message look like, etc.).

I'm a newbie when it comes to web-application authentication, so what I'm requesting may already exists in some standards document elsewhere.  If this is the case, please point me to those.  I'm not looking for a hyperlink to a big document such as the OAuth2 specification or the Torrii Github project.  I only need to know the messages this addon will be sending.  Thanks in advance.

**Comment by ghost** [comment]
@ptmoy2 I think you need https://github.com/jpadilla/ember-simple-auth-token/tree/master/server/mocks/api

**Comment by eluciano11** [comment]
Hi @ptmoy2 

what's the login HTTP message look like -> The addon will do a `POST` to the endpoint you specified in the configuration. It will include the `identificationField` and the `passwordField` you specified in your simple auth token configuration. Example: `{email: example@gmail.com, password: 123456}`

where in the HTTP message does the token have to go in the server-reply message -> your token should be in the response you give to the frontend. The property name you use for the value of the token should match the `tokenPropertyName` you specified in the configuration. Example: `{token: 'JWT sometoken'}`

where's the token in the subsequent authorize messages -> The token will be passed in your request header. You can specify the `authorizationPrefix` and the `authorizationHeaderName` in your configuration. Example: `Authorization: JWT sometoken` 
*_Note: With ember simple auth 1.0 you need to extend your adapter to use the DataAdapterMixin. See #96 *_

what's the logoff message look like -> This addons doesn't send a request to the backend to invalidate the token it just gets rid of it when you do `this.get('session').invalidate()`. From that point on no token will be present in the Request Headers and the user won't be able to access the routes that need the `ApplicationRouteMixin`.

Hope this helps!

I will close this issue because it's not a problem of the addon itself.
