### ISSUE TITLE
The authenticator "authenticator:jwt" rejected to restore the session - invalidating…

### ISSUE THREAD

**Issue by dbinetti** [fenichelar/ember-simple-auth-token#126]
I am getting this error: `The authenticator "authenticator:jwt" rejected to restore the session - invalidating…` which happens any time i try to access something from the API.  It says it's happening at ember-simple-auth/internal-session line 67  Any thoughts on how to debug?  

Ember 2.3.0
Ember Data 2.3.3
Simple Auth 1.0.0

**Comment by tgsoverly** [comment]
I am also getting this behavior

@dbinetti I set a break point at that log message and ran the restore function in the console and it indicated that the token was expired.  This was because I didn't set the "exp" config value to "expires_in" which was what my backend was handing back for that property.

**Comment by dbinetti** [comment]
@tgsoverly Thanks much for the pointer -- that was in fact my issue.  This fixed it.  Closing

**Comment by beerlington** [comment]
I ran into this issue as well and just wanted to leave a note. My token exp value was in seconds, not milliseconds, and I need to set the `timeFactor` option to `1000`. This is in the docs, but I missed it during install.

**Comment by yaodong** [comment]
To developers who use Flask-JWT and have the same issue, here is what your need in your Ember `enviroments.js`:

``` js
'ember-simple-auth-token': {
  tokenPropertyName: 'access_token',
  timeFactor: 1000
}
```
