### ISSUE TITLE
Failed token refresh doesn't invalidate.

### ISSUE THREAD

**Issue by kris-ellery** [fenichelar/ember-simple-auth-token#130]
First of all, thanks for a great plugin!

I have some questions:

1) What should be the HTTP status code when authorization or token refresh fails? Currently using 422 per ember docs, but not 100% sure which one I should use.

2) When server returns error on token refresh, the session doesn't get invalidated. I'd assume it should logout the user.

3) What happens if a user walks away for longer than token expiration? Is token getting continuously refreshed? Is there a way to logout user due to inactivity?

**Comment by eluciano11** [comment]
Hi @KrisOlszewski , we don't require specific HTTP codes to be sent back to the addon. For example if an authorization failed because the credentials were wrong anything with an HTTP 4xx should work. HTTP 4xx indicate that an error occurred on the client and HTTP 5xx indicate that an error occurred on the server. When the token refresh fails your backend should send an HTTP 403 Forbidden to the client. When the refresh fails the token gets expired but your session is not invalidated automatically so the user doesn't get logged out. Currently we don't support login out do to inactivity. If your `refreshAccessToken` is set to `true` in your `environment.js` the token should continue to refresh while the page is open.

Hope this helps!

**Comment by kris-ellery** [comment]
Hi @eluciano11, thanks for the response! I'll have to implement custom solution to log out users due to inactivity or failed token refresh. I have some strict requirements in current project and it's a must-have feature.

**Comment by eluciano11** [comment]
@KrisOlszewski No problem. Any PR is welcome! If you can implement these features in a way that users of the addon can opt-in to them it would be awesome.

**Comment by basz** [comment]
@KrisOlszewski would you mind shared your custom solution? How do you monitor that the token gets expired and then invalidate the session? I'll have the same requirement

thanks

**Comment by eluciano11** [comment]
Hi @basz you can checkout #150 (Token Invalidation) and #152 (Token Invalidation when Idle). Hopefully we'll ship these features this week.

**Comment by basz** [comment]
hi I find those just wrote this comment. looks awesome. thanks

**Comment by kris-ellery** [comment]
@basz I haven't been able to create a custom solution. My project moved in time, so kinda hoping this feature will be added to next Ember Simple Auth and/or Ember Simple Auth Token releases.
