### ISSUE TITLE
My POSTs don't seem to contain the Authorization Bearer.

### ISSUE THREAD

**Issue by NullVoxPopuli** [fenichelar/ember-simple-auth-token#137]
GET requests contain the authorization header, but POSTs do not. Is this intentional? I would think all requests of any verb would contain the authorization bearer. 

I'm just using the token authenticator.

Here is my project if you want to take a look at my configuration: https://github.com/NullVoxPopuli/aeonvera-ui

**Comment by eluciano11** [comment]
Hi @NullVoxPopuli , the add-on's normal behaviour sends the token on every request to the backend after a successful authentication. The add-on is currently working. I've taken a look at your app and the configuration looks good to me. The only think that I noticed is that you use `this.get('session').authenticate('authenticator:devise', data);` on your login route instead of the addon's `this.get('session').authenticate('authenticator:token', data)`. I have never used `authenticator:devise` before. Could or have you try using `authenticator:token` to see if there's any difference?

The other thing that I have never changed is `session: 'session:application'`, `store: 'session-store:local-storage'` I don't really know if that affects the add-on in some way.

**Comment by NullVoxPopuli** [comment]
oh thanks! I forgot to check that one. I was actually using devise auth before I found this addon, and have been migrating my app over. (devise auth doesn't auth every request, which is annoying). I'll give your suggestions a go! stand by. :-)

**Comment by NullVoxPopuli** [comment]
Ok, so... here is a GET request (after logging in)
![image](https://cloud.githubusercontent.com/assets/199018/14015703/6641ae4e-f191-11e5-92da-7841b2ca2741.png)

And here is a POST:
![image](https://cloud.githubusercontent.com/assets/199018/14015716/801dbe8e-f191-11e5-9dee-00514f856b52.png)

Upon refreshing the page (to test if one of my requests de-auth'd me):
![image](https://cloud.githubusercontent.com/assets/199018/14015727/9d119182-f191-11e5-81db-76d4af066385.png)

The Auth bearer is still present.

It just seems that on POSTs....
wait...
o
m
g

I forgot that on _that_ particular POST, I'm constructing the AJAX myself due to JSON API / Ember Data not having a unified way to send multiple resources in a create request..... 

Well, that's embarassing.

Here is my jQuery ajax with the header set (for future wanderers)

```

    let authToken = this.get('session.data.authenticated.token');

    let promise = new Ember.RSVP.Promise((resolve, reject) => {
      Ember.$.ajax({
        type: ajaxVerb,
        url: config.host + '/api/orders',
        data: jsonPayload,
        beforeSend: xhr => {
          xhr.setRequestHeader("Authorization", "Bearer " + authToken);
        }
      }).then(response => {
        let id = response.data.id;
        store.pushPayload(response);
        let order = store.peekRecord('order', id);
        resolve(order);
      }, error => {

        reject(error);
      });
    });
```
