### ISSUE TITLE
Drop support for normal token authentication

### ISSUE THREAD

**Issue by leo** [fenichelar/ember-simple-auth-token#151]
@jpadilla and I have already talked about this topic a while ago: Meanwhile, ember-simple-auth-token isn't really needed anymore for normal token authentications. Why not? Because ember-simple-auth's `OAuth2PasswordGrantAuthenticator` also supports token authentication.

Because of this, my personal opinion is that ember-simple-auth-token should encourage users to use the built-in solution instead of an addon. Besides of that, ember-simple-auth-token could focus completely on JSON Web Tokens (since there's a fundamental difference between the tokens you're generating with `OAuth2PasswordGrantAuthenticator` and JSON Web Tokens):

OAuth2 with tokens are still sessions that are being saved to the DB, only with tokens. But [JWTs](https://medium.com/@leo/why-json-web-tokens-are-truly-awesome-23fb80b7fc20#.lodwogl8r) are self-contained, so password and username are part of the token itself. So no need to save sessions to the DB. Because of that, ember-simple-auth will still be needed if you want to implement actual JSON Web Tokens into your Ember app.

**Comment by eluciano11** [comment]
How should this be managed?

I think that if we drop support for normal tokens it should be done on the 3.0 release. This would be a major breaking change and we should give the users time to migrate their apps to `OAuth2PasswordGrandAuthenticator`. We could add deprecation warnings on the 2.0 release.

@leo @jpadilla thoughts?

**Comment by leo** [comment]
@eluciano11 Exactly my opinion!

**Comment by acorncom** [comment]
A question here. I remember seeing that @jpadilla wasn't heavily using this add-on, should we consider offering to merge it with the main ember-simple-auth repo? I can start that discussion @jpadilla if you want me to ...

**Comment by jpadilla** [comment]
The original idea behind this package was to allow easy customization of an authenticator for backends with token authentication. For example, Django REST framework has built in support for simple token authentication, not OAuth2, or JWT or anything fancy. I now argue that for cases like that I'd rather just build my own custom authenticator, instead of possibly installing this one, and creating a custom authenticator to override and customize. The token authenticator in this package aims to be as "dumb" as possible, while ESA's `OAuth2PasswordGrantAuthenticator` obviously follows the OAuth2 spec closely.

Having said this, we could deprecate our token authenticator, in favor of people just building their own and just focus on the JWT one. I'd like to know of anyone using our `TokenAuthenticator`.

@acorncom I'm personally not working on any project using this package, that's why @eluciano11 has been helping out. I support, encourage and strongly favor the encapsulating new behavior in a package like ours rather than adding additional functionality directly into core. If there's genuine desire to merge this into core, because it would be better maintained, supported, etc than it currently is, I'd definitely be opened to talk.

**Comment by leo** [comment]
Closing this now, as I don't have a need for it anymore. Thanks everyone!
