### ISSUE TITLE
Auth error Error: Token is empty. Please check your backend response

### ISSUE THREAD

**Issue by mtep** [fenichelar/ember-simple-auth-token#161]
I have a problem I have no idea what is wrong.

After get at my token endpoint(Json API) in JWT token mode(authenticator:jwt) :
{
  "status": true,
  "data": [
    {
      "attributes": {
        "expire": 1464016623
      },
      "type": "tokens",
      "id": "JSON WEB TOKEN here"
    },
    {
      "attributes": {
        "expire": 1464017163
      },
      "type": "refresh_token",
      "id": "JSON WEB TOKEN here"
    },
    {
      "type": "roles",
      "id": "role"
    }
  ]
}
I have an exception Auth error Error: Token is empty. Please check your backend response;
In case of having token with authenticator:token, everything is allright.
Thank You for help.

**Comment by eluciano11** [comment]
Hi, I believe that the problem here is that this library doesn't support JSON API out of the box. You'd have  to extend the `jwt` authenticator. The `handleAuthResponse` is expecting a JSON response with the key `token` in it (https://github.com/jpadilla/ember-simple-auth-token/blob/master/addon/authenticators/jwt.js#L355). Since the JSON API structure has the data within the `data` key it will not be found and the error is displayed. `authenticator:token` doesn't do this verification because it doesn't refresh the token.

If your token doesn't need to be refreshed you should continue using the `authenticator:token` but that implementation will soon be dropped  so you might want to use this: https://ember-simple-auth.com/api/classes/BaseAuthenticator.html

Hope this helps!
