### ISSUE TITLE
how does refreshing a token make my app secure?

### ISSUE THREAD

**Issue by jonnedeprez** [fenichelar/ember-simple-auth-token#162]
I may be missing something, but It's not clear to me how the current implementation of refreshing tokens improves the security of an application. I thought the reason to let a token expire was to prevent an intruder that somehow managed to intercept your access token from stealing your identity _indefinitely_. But if that intruder can use the same access token to simply refresh it on another endpoint before it expires, the protection can easily be bypassed. The only advantage here is that if a lazy intruder waits for a couple of weeks before he attempts to break in, he will fail! Not very useful, I'd say...
Wouldn't a better strategy be to use 2 different tokens? An access token that is used to access protected resources but that expires frequently, and a refresh token that never or almost never expires, but is only used to refresh the access token (as in [https://auth0.com/docs/refresh-token]).

**Comment by eluciano11** [comment]
Hi, this library contains two implementations one of the if for simple token authentication (this one doesn't do any refreshes) and a JWT implementation. The blogpost you're referring to explains JWT and our current implementation in `jwt-authenticator` does the strategy you're suggesting (https://github.com/jpadilla/ember-simple-auth-token/blob/master/addon/authenticators/jwt.js). The support for simple token authentication will be dropped soon (https://github.com/jpadilla/ember-simple-auth-token/issues/151).

Hope this helps.
I'm closing this issue for now because it's not a library issue.

**Comment by jonnedeprez** [comment]
Actually, my point was that you _claim_ that you implement that strategy in jwt.js, but that in reality you don't (no offense!). Your implementation of the JWT authenticator can indeed refresh the token, but it does so using the token as configured by tokenPropertyName (i.e. the access token). IMHO, this refreshing strategy doesn't improve security, because it also allows the token thief to call refresh.

**Comment by evoactivity** [comment]
@eluciano11 I see this is an old issue, and was closed, but as @jonnedeprez restated, that is not what is currently implemented. My API has JWT implemented to give a short expiring JWT and a refresh token. Right now this library tries to use the JWT not the refresh token.

**Comment by eluciano11** [comment]
Yeah, after looking more into it @jonnedeprez was right. The tokens are getting mixed up. I haven't had time to work on this but if you have time to fix this we will welcome you PR.

**Comment by evoactivity** [comment]
@eluciano11 I've already forked ;) I should be able to have a look over the next few days.

**Comment by eluciano11** [comment]
@evoactivity awesome, thank you!

**Comment by jonnedeprez** [comment]
Shortly after I created this issue, I wrote my own JWT authenticator and token authorizer that solve it. @evoactivity, if you're planning to work on this, I'll share what I have

**Comment by jonnedeprez** [comment]
Feel free to cherrypick from this [gist](https://gist.github.com/jonnedeprez/b6831dbe8fc304095d7ed9f6442bb534)

**Comment by evoactivity** [comment]
Thanks @jonnedeprez 
It looks similar to what I was planning on doing, so should prove helpful :)

**Comment by evoactivity** [comment]
#190 Made a PR @eluciano11

**Comment by sdhull** [comment]
@jonnedeprez @evoactivity I've been down the jwt / refresh token rabbit hole today and one thing I haven't really seen addressed is this: if an attacker can steal your access token, why can't they also steal your refresh token?
Is this "added security" just an additional degree-of-difficulty sort of thing or does it somehow prevent attacks? In fact, doesn't the addition of a second token technically increase the surface area for attack, since an attacker could now steal your identity by getting _either_ your access token or your refresh token?

One interesting thing I found today is [this answer on SO](https://stackoverflow.com/a/26834685/495637) that seems to imply using an access token to refresh itself is fine. From reading the [article linked at the bottom of the readme](https://auth0.com/blog/refresh-tokens-what-are-they-and-when-to-use-them/), it suggests that you should store refresh tokens server-side so they can be revoked, however I don't see why you wouldn't just assign & store JWT id's (`jti`) and use them to the same effect. That is to say, if the "security" you gain from refresh tokens is that they are revokable, you could implement revokable access tokens in much the same way.

**Comment by jonnedeprez** [comment]
@sdhull If you mean with 'stealing' that an attacker can read your local browser data, there's indeed no difference, but if we assume that modern browsers are reasonably well protected in this area, then a difference is that an access token is exchanged between browser and server all the time. i.e. with every request, whereas a refresh token is exchanged only very rarely. If an attacker breaks the SSL protection and reads the token, he would still need to be very lucky to have read the refresh request that would give him access without expiry.

**Comment by sdhull** [comment]
> If an attacker breaks the SSL protection

Is this really more likely than an attacker somehow gaining access to local browser data? If an attacker can break SSL protection doesn't it seem like all bets are off at that point? Or is it the case that they might be able to break SSL protection for a single request but not others? Or it takes a ton of resources per request to break SSL? Or (more likely imo) if they break SSL for a request, then they can snoop all traffic to that domain (implies you have discovered the private key for that domain's cert)?

From all my questions it's probably pretty obvious I'm not in infosec 😜 

Sidenote: the article linked mentions (in **bold!**) a refresh token "must be **stored securely**" but doesn't really go into any detail about what exactly the author meant by that... and again, if storing it securely helps prevent attack, then why not store the jwt itself securely and make it longer-lived?
