### ISSUE TITLE
Possible issue with latest ESA Beta

### ISSUE THREAD

**Issue by cloke** [fenichelar/ember-simple-auth-token#189]
I've been experiencing issues with ESA not redirecting to the correct route on login/logout. Basically an attempt is made to transition to the desired route, but then the transition is killed. There are a few other people reporting the same issue and it appears that we are all using ESA Token.

https://github.com/simplabs/ember-simple-auth/issues/1128

**Comment by lionelrudaz** [comment]
Hi guys,

As explained in the issue on ESA, I've got the same problem. Any thoughts?

**Comment by jpadilla** [comment]
I haven't tried using the latest beta. We'll need to update this addon to use the latest beta, perhaps run the dummy app and tests and see if anything breaks. I usually go through ESA's changelog and make sure we're up to date.

Anyone want to step up and help?

**Comment by lionelrudaz** [comment]
Thanks @jpadilla. I'm not sure I've got the skills to help you, but have some free time tomorrow night. Let me know if there's anything I can do.

**Comment by cloke** [comment]
After some work I no longer have this issue, but I am not exactly sure what I did to resolve it. My application route was including several mixins from ESA which I think was a mistake. I now only include ApplicationRouteMixin from ESA which may have been the solve, but I am not 100% sure.

On a related note...

Getting the tests to run took some time. I was getting qunit and babel error all over the place. I updated the project dependencies to only work with Ember > 2.x and I could get the tests to run, but then they all fail with server errors. Is there documentation related to running the tests?

**Comment by Baukereg** [comment]
We experienced the same issue and actually found out that, after login, the transition is happening, but somehow the model hook of that route breaks.

To make it even more awkward, it only happens if we do a findRecord on the store. The store doesn't seem to return a valid promise, it never resolves, so the model hook of the route never resolves.
As soon as I remove ```return``` (so the findRecord is still executes, just not used as a promise by the model hook), the transition works fine.

I'll propably go back to a previous version of ESAT for now.

**Comment by Baukereg** [comment]
We actually had a similar problem and found out it had something to do with rendering the next route with something that did work pre-Glimmer2 but now failed after updating to the latest version of Ember.
