### ISSUE TITLE
Refresh Token not being sent for refresh

### ISSUE THREAD

**Issue by justinboohan** [fenichelar/ember-simple-auth-token#197]
I don't know if I have the wrong end of the stick here but my understanding of jwt is that the refresh token should be sent to the refresh token endpoint once the access token is due to expire. When I use ember-simple-auth-token the access token is being sent to the refresh endpoint. 

My login method receives a response like:

 {"token":"<accessTokenValue>","refreshToken":"<refreshTokenValue>"}

When the refresh is attempted it's using the "token" value and not the "refreshToken" value as I expected it would. 

My environment.js settings: 

  ENV['ember-simple-auth'] = {
    authorizer: 'authorizer:jwt'
  };

  ENV['ember-simple-auth-token'] = {
    serverTokenEndpoint: 'http://localhost:8080/api/auth/login',
    identificationField: 'username',
    passwordField: 'password',
    refreshTokenPropertyName: 'refreshToken',
    authorizationPrefix: 'Bearer ',
    authorizationHeaderName: 'X-Authorization',
    headers: {
      'X-Requested-With': 'XMLHttpRequest'
    },
    serverTokenRefreshEndpoint: 'http://localhost:8080/api/auth/token',
    tokenExpireName: 'exp',
    refreshLeeway: 20
  };

**Comment by adam820** [comment]
I, too, am running into this. For testing I'm setting my 'expiration' value low on the initial returned access/refresh tokens (1 min, 2 min respectively). When ESAT goes to refresh the token, Chrome is showing that the POST to the server is sending the access token, not the refresh token. My API backend (_flask-restplus w/ flask-jwt-extended_) requires a refresh token on the `/auth/refresh` path. Oddly, however, it's throwing an error that the Authorization Header is missing, not that it's the incorrect token (so it's not even making it to the decoding step).

If I do the operation manually with Postman (POST to `/auth` -> get tokens -> POST to `/auth/refresh` with Authorization header: `Bearer + {refresh token}`), I successfully get new tokens back as expected. It appears either we're misunderstanding something in ESAT, or it's not operating correctly (I'm hoping the former). 

My config:
```
ENV['ember-simple-auth'] = {
    authorizer: 'authorizer:token'
  };

  ENV['ember-simple-auth-token'] = {
    serverTokenEndpoint: ENV.REST_HOST + '/auth',
    identificationField: 'username',
    passwordField: 'password',
    tokenPropertyName: 'access_token',
    refreshTokenPropertyName: 'refresh_token',
    authorizationPrefix: 'Bearer ',
    authorizationHeaderName: 'Authorization',
    headers: {},

    //JWT-specific options
    refreshAccessTokens: true,
    serverTokenRefreshEndpoint: ENV.REST_HOST + '/auth/refresh',
    tokenExpireName: 'exp',
    refreshLeeway: 0
  };
```

(Otherwise, I'm really liking this addon; great work!)

**Comment by alechirsch** [comment]
@adam820  @justinboohan This is not a bug. The latest release on npm does not have the refresh token functionality yet, take a look at the differences between README.md on github and the README on npm. If you pointed the package directly to the github repository, you should see that the refresh token is working as expected.

**Comment by justinboohan** [comment]
Thanks for that @alechirsch I'll try the github package now. @adam820 my api backend doesn't require the authorization token on the refresh endpoint so I can't help you there

**Comment by adam820** [comment]
Based on what @alechirsch says, that will very likely fix the issue. Thanks for the help!
