### ISSUE TITLE
Ember 2.16 new MODULES API IMPORT.

### ISSUE THREAD

**Issue by ghost** [fenichelar/ember-simple-auth-token#208]
Any hint for the transition to the new import module system described here? https://emberjs.com/blog/2017/09/01/ember-2-15-released.html

**The 2.16 stable is approaching...**

I have this:

`Uncaught Error: Could not find module `ember` imported from `ember-simple-auth-token/authenticators/token``

**Comment by jalcine** [comment]
Might have to propose a PR for this tbh

**Comment by jherdman** [comment]
I looked into this a bit, part of the problem seems to be that the tests stub things pretty extensively which is making it hard to upgrade things. I'm contemplating rewriting the tests so that they're acceptance-based, but I'm not sure if that'll pooch the Github pages. Would anyone be able to offer some insight here?
