### ISSUE TITLE
[Fastboot] Doesn't allow arbitrary exp date

### ISSUE THREAD

**Issue by musaffa** [fenichelar/ember-simple-auth-token#250]
Ember runloop's `later` function used in [jwt authenticator](https://github.com/jpadilla/ember-simple-auth-token/blob/5102353fc2178582c3f9aaa86fa12995a6072603/addon/authenticators/jwt.js#L319) expects 32 bit signed integer in node.js environment as its param. If 32 bit signed integer limit is exceeded, then a `TimeoutOverflowWarning: [num] does not fit into a 32-bit signed integer` error is triggered that never stops.

Max number allowed in 32 bit signed integer = 2^31 - 1 = 2,147,483,647

2,147,483,647 / (24 * 60 * 60 * 1000) ~ 24.855 days. Currently, exp date should be less than 25 days in Fastboot settings.

Here's a [sample app](https://github.com/musaffa/fastboot-auth) that demonstrates the issue. After running the server, click sign in. Now you will see a sign out link. Reload the browser and have a look at the terminal.

**Comment by fenichelar** [comment]
I'm not sure that there is anything to do in this library other than maybe add a warning in the documentation. However, 25 days is quite a long time for a JWT to be valid.... typical values are measured in minutes.

I'm not sure why `Ember.later` expects a 32 bit signed integer in a Node.js library, but maybe open an issue there to see if that can be changed because Node.js uses double precision floats under the hood.
