### ISSUE TITLE
Refresh Token quick question

### ISSUE THREAD

**Issue by jrdn91** [fenichelar/ember-simple-auth-token#94]
I just have two quick questions about the automatic token refresh for JWTs.

First I see I can pass in the `serverTokenRefreshEndpoint`, is there a reason I would want to use a different endpoint than `serverTokenEndpoint`, also if I don't supply this does it default to what's defined in the `serverTokenEndpoint` key or does it default to anything at all?

**Comment by albertovasquez** [comment]
One thing to look at is what contents you are returning with the tokenendpoint - are you returning user data and have to query a db?  If so then maybe you don't want to do it with each refresh.   That data would be part of the token data so there would be no need.  

Also the server token endpoint I'm assuming you are taking a username password or some way to validate that a token can be created.  You will not be passing username/pass with the refreshes.  It seems to me you are just doing different logic on the refresh due to the content you have on hand.
